#!/usr/bin/env bash
#This script is displaying "Best School" 10 times using a While loop
i=0
while [ "$i" -lt 10 ];
do 
if [ "$i" == 4 ]
then
echo "bad luck"
elif [ "$i" == 8 ]
then
echo "good luck"
fi
echo "Best School"
i=$((i+1))
done
