#!/usr/bin/env bash
#This script is displaying "Best School" 10 times using a While loop
i=1
while [ $i -lt 21 ];
do
case $i in
4)
echo "$i"
echo "bad luck form China"
;;
9)
echo "$i"
echo "bad luck form Japan"
;;
17)
echo "$i"
echo "bad luck from Italy"
;;
*)echo "$i"
;;
esac
i=`expr $i + 1`
done
