#!/usr/bin/env bash
#Displays hours from 0 to 12 
#Displayminutes from 1 to 59
hr=0
while [[ $hr -le 12 ]];
do
echo "Hour: $hr"
hr=$((hr+1))
min=1
while [[ $min -le 59 ]]; 
do 
echo "$min" 
min=$((min+1))
done
done
